Effective: June 7, 2011
Last Modified: December 28, 2011

Please read this User Content Submission Agreement carefully because it is a part of the <a href="<?php echo getUrl("terms-of-service/"); ?>">Terms of Service Agreement</a> and represents your legally binding agreement with us ("<u>Submission Agreement</u>") regarding your submission (and our display and distribution) of content to the Site via certain technology, functionality and/or features we make available to you so you can upload and post such content for display via the Site (collectively, the "<u>User Content Submission Features</u>"), and this Submission Agreement applies regardless of what type of Device you use to submit content to the Site. Unless defined separately, terms used in this Submission Agreement are defined in our <a href="<?php echo getUrl("terms-of-service/"); ?>">Terms of Service Agreement</a>.

When you submit User Content, or by using or attempting to use the User Content Submission Features, you are signifying your agreement with and acceptance of all terms and conditions of this Submission Agreement as well as the terms and conditions contained in the <a href="<?php echo getUrl("terms-of-service/"); ?>">Terms of Service Agreement</a> that govern your legal and contractual relationship with the Parent Company.

We have the right to change the terms and conditions of this Submission Agreement at any time as described in our <a href="<?php echo getUrl("terms-of-service/"); ?>">Terms of Service Agreement</a>. If you do not agree with all the terms and conditions of this Submission Agreement at any time, including, without limitation, those times when we make changes, do not use, do not attempt to use, and immediately discontinue your use of, the User Content Submission Features, because if you do any of these things you are agreeing to be bound by all of the terms and conditions of this Submission Agreement, including, without limitation, any changes we have made.

<b>IMPORTANT NOTE:</b> You must meet the Age and Other Eligibility Requirements in Section 2 of this Submission Agreement and each and every time you submit or attempt to submit User Content, among other things, you will be asked to confirm your compliance.

<ol><li><h2>Submitting User Content.</h2></li>
The term <u>"User Content"</u> means and refers to any and all content, media and materials you submit for posting on the Site using the User Content Submission Features, including, without limitation, still photographs, writings, spoken statements, music, audio, video, video recordings, audio-visual works and recordings, slides, portraits, animated and/or motion pictures, caricatures, likenesses, vocal or other sounds, sound recordings, voices, voice reproductions, computer graphics and visual effects, as well as any accompanying documentation, packaging or other materials, tangible or intangible, and to all derivative works, translations, adaptations or variations of same, regardless of the tangible medium, broadcast medium, format or form, now known or hereinafter developed or discovered, and regardless of where produced, on location, in a studio or elsewhere, in black-and-white or in color, alone or in conjunction with other work, characters, real or imaginary, in any part of the world. User Content is also considered a "Posting", as such term defined in the <a href="<?php echo getUrl("terms-of-service/"); ?>">Terms of Service Agreement</a>, and therefore, all terms and conditions contained within the section of the <a href="<?php echo getUrl("terms-of-service/"); ?>">Terms of Service Agreement</a> entitled "Postings" shall apply to all User Content you submit pursuant to the terms and conditions of this Submission Agreement for Posting to the Site.

Each time you upload or submit User Content (or if you attempt to do so) you will be confirming your acceptance of, and agreement to be bound by, all the terms and conditions of this Submission Agreement. Instructions for uploading User Content can be found on the Site's web page for the upload of User Content. To be considered for posting and display to the public, User Content must meet all the specifications and requirements relating to formatting, compatibility, operating characteristics and submission which can also be found on the Site's web page for the upload of User Content. In order to submit User Content, you will also need to meet our Age Requirements (see Section 2 below).

When you submit User Content you may also be asked to provide some information about you and your submission. This may include, without limitation, such things as a descriptive title, some information about the User Content, length, your location and/or similar information. By submitting User Content, you are also agreeing and you understand that the term "User Content" also includes, without limitation, and refers to all of the information you submit or we may receive that is related to your submission. Always keep a copy of anything you send because we are not responsible for lost, damaged, misdirected, unusable or unreadable User Content. Proof that you submitted User Content does not constitute proof that we received anything.

<li><h2>Age and Other Eligibility Requirements.</h2></li>
By submitting User Content pursuant to the terms and conditions of this Submission Agreement you are certifying that you satisfy the age and other eligibility requirements set forth in the <a href="<?php echo getUrl("terms-of-service/"); ?>">Terms of Service Agreement</a>.

<li><h2>User Content Standards; Unauthorized Content.</h2></li>
You are solely responsible and liable for your communications and submissions (and the consequences) made under your name, user name, email address, password and your registration and profile information, if any. User Content does not reflect the views of the Parent Company, and neither the Parent Company, nor any of the the Affiliates, represents or guarantees the truthfulness, accuracy, or reliability of any User Content, or endorses or supports any opinions expressed in any User Content. In no event shall the Parent Company or the Affiliates have or be construed to have any responsibility or liability for or in connection with any User Content. If we determine, in our sole discretion, you have not met the Age Requirements (see Section 2 above) or if, in our judgment, you or any User Content you submit violates this Submission Agreement, we reserve the right, at any time, without notice and without limiting any and all other rights we may have under this Submission Agreement, at law or in equity, to (a) refuse to allow you to submit further User Content, (b) remove and delete your User Content, (c) revoke your registration and right to use the User Content Submission Features and (d) use any technological, legal, operational or other means available to enforce the terms of this Submission Agreement, including, without limitation, blocking specific IP addresses or deactivating your registration, access using your e-mail address, your user name and password.

We make no claim the User Content Submission Features or any User Content are appropriate for any particular purpose or audience, or that any video, software or our User Content Submission Features may be accessed, used or downloaded outside of the United States, which may not be legal for certain persons or in certain countries and you do so at your own risk. You are responsible for compliance with the laws of your jurisdiction. The United States controls the export of products and information and you agree to comply with such restrictions and not to export or re-export any User Content including videos, information, software, materials, products or services to countries or persons prohibited under the export control laws and regulations.

You agree you will not submit or attempt to submit, and we have the right to reject, refuse to accept, remove or otherwise handle as the Parent Company deems appropriate, any "<u>Unauthorized Content</u>" which is defined as any User Content that is or could be construed as violating any of the terms and conditions of this Submission Agreement, and/or any of the terms and conditions set forth in our <a href="<?php echo getUrl("terms-of-service/"); ?>">Terms of Service Agreement</a>, including, without limitation:

<ul><li>infringing on a third party's copyright or other intellectual property rights;</li>
<li>causing harm, harassing anyone or which may prevent, prohibit, inhibit, restrict or otherwise impair others from using or enjoying the Site;</li>
<li>unauthorized access to the User Content Submission Features or information of other users;</li>
<li>the modification, impairment, disruption, alteration or interference with the use, features, functions, operation or maintenance of the User Content Submission Features; or</li>
<li>any requirements, rules, terms or conditions that may be applicable to the User Content Submission Features.</li></ul>
Neither the Parent Company nor the Affiliates control any User Content submitted, although we may use both automated and manual means of reviewing User Content in order to prevent Unauthorized Content from appearing and being displayed on our Site. The Parent Company reserves the right to review any submitted User Content and to delete, remove, move, edit or reject, without notice to you, any User Content that we deem, in our sole discretion, abusive, defamatory, obscene, pornographic, in violation of copyright, trademark or other intellectual property rights, to be in violation of this Submission Agreement or to be unacceptable to the Parent Company or its Affiliates, for any reason or for no reason whatsoever; provided, however, that the Parent Company and the Affiliates shall have no obligation or liability to you for failure to do so or for doing so in any particular manner. If the Parent Company receives notice of any claim of infringement that satisfies specific legal requirements, such as notice and takedown requirements under U.S. copyright law (see Section 4 below), we may remove User Content associated with such claim. The Parent Company reserves the right to provide information to law enforcement officials, governmental agencies and pursuant to judicial or regulatory compulsion, to protect their respective interests, the Site or to comply with legal, regulatory, audit and compliance obligations.

<li><h2>Copyright Infringement.</h2></li>
If you believe any User Content violates the copyright of any other party, you can notify us by complying with the procedures set forth in our <a href="<?php echo getUrl("copyright-compliance-policy/"); ?>">Copyright Compliance Policy</a>.

<li><h2>Rights Granted to the Parent Company.</h2></li>
In connection with all User Content you submit using the User Content Submission Features, you grant to the Parent Company and the Affiliates, the unqualified, unrestricted, unconditional, unlimited, worldwide, irrevocable, perpetual and royalty free right, license, authorization and permission, in any form or format, on or through any media or medium and with any technology or devices now known or hereafter developed or discovered, in whole or in part, to host, cache, store, maintain, use, reproduce, distribute, display, exhibit, perform, publish, broadcast, transmit, modify, prepare derivative works of, adapt, reformat, translate, and otherwise exploit all or any portion of your User Content on the Site (regardless of the Device through which the Site may be accessed) and any other channels, services, and other distribution platforms, whether currently existing or existing or developed in the future, of the Parent Company and the Affiliates (collectively, the "<u>Platforms</u>"), for any purpose whatsoever (including, without limitation, for any promotional purposes) without accounting, notification, credit or other obligation to you, and the right to license and sub-license and authorize others to exercise any of the rights granted hereunder to the Parent Company and Affiliates, in our sole discretion. For the avoidance of doubt, without limiting the generality of the rights granted to the Parent Company and the Affiliates, these rights include, without limitation, the right to distribute and synchronize all or any portion of your User Content in timed relation to any other visual elements; to web cast, pod cast, re-publish, re-broadcast, re-platform, port, syndicate, route, and link to and from all or any portion of your User Content; to encrypt, encode and decode, and compress and decompress all or any portion of your User Content; to edit, mix, combine, merge, distort, superimpose, create or add special effects, illusions and/or other material to or of all or any portion of your User Content; to create composite, stunt, comic or unusual photographs, videos, animations, motion pictures and/or voice reproductions from all or a portion of your User Content; and to excerpt and/or extract portions of your User Content in order to host, store, index, categorize and display your User Content on or through the Platforms.

By submitting User Content, in addition to the rights, licenses and privileges referred to above, you are also granting the Parent Company and the Affiliates, the unqualified, unrestricted, unconditional, unlimited, worldwide, irrevocable, perpetual and royalty free right, license, authorization and permission to use and refer to your name, logo, marks, image, characteristic or other distinctive identification in presentations, marketing materials, customer lists and financial reports, to do, perform, take advantage of and exploit any and all of the rights set forth herein in connection with the marketing, advertising and promotion of the Platforms, and any products, goods, features, functions, capabilities and/or services associated with the Parent Company and Affiliates and to use and otherwise exploit any ideas, concepts, content, material, expression or form of expression, in whole or in part, contained in your User Content, for any purpose whatsoever, without any credit, compensation or accounting to you, in products or services developed by the Parent Company and the Affiliates, without limitation or restriction whatsoever.

The rights, licenses and privileges described in this Submission Agreement and granted to the Parent Company and the Affiliates, shall commence immediately upon submission of your User Content to or through the User Content Submission Features and continue thereafter perpetually and indefinitely, regardless of whether you continue or remain a registered user or not, unless and until terminated, in whole or in part, by the Parent Company on notice to you. Notwithstanding the foregoing, you acknowledge and agree that neither the Parent Company, nor the Parent Company or the Affiliates, shall be required or have any obligation to host, index, display, accept or use any submitted User Content (or take advantage of any or all of the particular rights and authorities granted or otherwise available) and the Parent Company may, in its sole discretion, remove or refuse to host, index, display, accept, use or do anything at all with respect to any User Content. Once you submit or attempt to submit User Content you shall have no right to prohibit, restrict, revoke or terminate any of the rights granted to the Parent Company or the Parent Company or the Affiliates. You are not entitled to and you will not receive any compensation or other consideration for your User Content or any use made of your User Content once submitted, except if an answer is published in a Parent Company book, as noted in the <a href="<?php echo getUrl("answer-guidelines/"); ?>">Answer Guidelines</a>. You also understand and agree that neither all or any portion of your User Content, nor any commercial, advertisement, promotional, marketing or other material associated with your User Content, need to be submitted for approval prior to use.

You hereby release the Parent Company and the Affiliates from any and all claims of any rights, encumbrances, liens, claims, demands, actions or suits which you may or can have in connection with your User Content, including, without limitation, any and all liability for any use or nonuse of the your User Content, claims for defamation, libel, slander, invasion of privacy, right of publicity, emotional distress or economic loss. the Parent Company, and the Parent Company and the Affiliates, have the right to assign, transfer, convey, license, sub-license and otherwise transfer, sub-contract, delegate, outsource or engage third parties to perform or benefit from all or any portion of its or their rights and/or obligations to any one or more other parties, without accounting, reporting, notification or other obligation or liability to you whatsoever, now or in the future. You also forever waive and relinquish all moral rights or droit moral now or hereafter recognized in connection with your User Content and the rights granted to the Parent Company and the Affiliates hereunder.

The Parent Company has the right to license, authorize and/or otherwise enter into agreements and arrangements with any Parent Company or the Affiliates to do or perform any of the activities, exercise any of the rights and/or undertake any of the responsibilities granted or imposed under this Submission Agreement, in whole or in part. To the extent the Parent Company does so, when you submit User Content each such Parent Company and Affiliate shall be entitled to exercise and benefit from the terms and conditions, rights, licenses and authorizations granted to the Parent Company hereunder and related thereto as if you had entered into this Submission Agreement with such Parent Company or Affiliate directly.

<li><h2>Ownership.</h2></li>
The Parent Company retains all right, title and interest in and to the User Content Submission Features, including, without limitation, to all associated intellectual property and proprietary rights existing anywhere in the world and you acquire no ownership, proprietary or other rights, title or interest in or to the User Content Submission Features.

Except for the licenses, authorizations, consents and rights granted hereunder and described in this Submission Agreement, as comprehensive and broad as they may seem or actually be, <b>the Parent Company acquires no title or ownership rights in or to any User Content you submit</b> and nothing in this Submission Agreement conveys to us any ownership rights in your User Content. the Parent Company is acting only as a host, bulletin board or conduit for submitted User Content, with all of the specific rights granted by you hereunder. Although by your submission of any User Content you are requesting and directing us and any of the Parent Company or the Affiliates with whom we have made arrangements, to take advantage of and exploit all of the rights and privileges granted hereunder (including, without limitation, the right to display and post the User Content on the Platforms), neither we, nor any of the Parent Company or the Affiliates have any obligation to do any of these things.

You must own the rights to the User Content you submit and the right to grant all of the authorizations, permissions, approvals, consents, rights and licenses as described in this Submission Agreement. If you do not exclusively own all of these rights, you must have all necessary authorizations, permissions, approvals, consents, rights and licenses from the owner(s) to enter into this Submission Agreement and perform and comply with all of its obligations. You represent, warrant and covenant to the Parent Company and the Affiliates and, by submitting User Content, you reaffirm each such representation, warranty and covenant, that (a) you are not a minor and you have the legal right and capability to enter into this Submission Agreement and perform and comply with all of its terms and condition or, if you are a teenager, your parent or legal guardian has agreed to this Submission Agreement on your behalf, (b) all of the information provided by you associated with your User Content is correct, complete and current, (c) your submission of any User Content does not violate this Submission Agreement, any rights of any other party, any of your obligations, any law or regulation or infringes upon or misappropriates any intellectual property, privacy, publicity or other rights of any party, (d) you make in the <a href="<?php echo getUrl("terms-of-service/"); ?>">Terms of Service Agreement</a>, including, without limitation, those relating to Postings and (e) you hold and will continue to hold all the ownership, license, proprietary and other rights necessary to enter into, authorize, grant rights and perform your obligations under this Submission Agreement as described. Upon the request of the Parent Company, you will furnish the Parent Company any documentation, substantiation and releases necessary and reasonably required to verify and substantiate your compliance with any or all of the terms and conditions of this Submission Agreement, including, without limitation, the foregoing representations, warranties and covenants. You represent and warrant that the submission of your User Content is not subject to or under the jurisdiction of any guild or union collective bargaining agreement, and you further acknowledge that the Parent Company and/or the Affiliates is not signatory to any such agreement. Notwithstanding anything to the contrary, you also understand and agree that the Parent Company and/or the Affiliates shall not be obligated or responsible for providing any guild or residual payments in connection with the submission and exploitation of the User Content.

You acknowledge that other persons may have submitted User Content to us, may have made public or developed, or may originate, submit, make public or develop, material similar or identical to all or a portion of your User Content or concepts contained therein, and you understand and agree you will not be entitled to any compensation because of the use or exploitation thereof and the submission of User Content, or any posting or display thereof, is not any admission of novelty, priority or originality. Even if you subsequently see or learn of a presentation, motion picture, still photograph, film, video or any other content which appears to incorporate any idea or concept or include anything similar or identical to that contained in any User Content you or anyone else submits, that is purely coincidental and unavoidable.

<li><h2>Consideration.</h2></li>
The Parent Company and the Parent Company reserve the sole and exclusive right to sell advertising and otherwise exploit, benefit from and/or realize revenue from the conduct of its business and operating the Site, the User Content Submission Features or other Platforms and any and all arrangements made with respect thereto, without accounting, obligation or liability to you, notwithstanding that your User Content may be displayed on or otherwise used by or in connection with the Site, the User Content Submission Features or other Platforms.  Users may also receive compensation for User Content they submit as further noted in the <a href="<?php echo getUrl("answer-guidelines/"); ?>">Answer Guidelines</a>.

<li><h2>Indemnification.</h2></li>
Your indemnification obligations under the <a href="<?php echo getUrl("terms-of-service/"); ?>">Terms of Service Agreement</a> include, without limitation, any third party claims arising from, related to or caused by your User Content, the submission of User Content and/or in any way associated with this Submission Agreement and/or the Site.

<li><h2>Disclaimers and Limitation of Liability.</h2></li>
THE USER CONTENT SUBMISSION FEATURES ARE PROVIDED "AS IS" WITH NO WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED AND YOUR USE OF THE USER CONTENT SUBMISSION FEATURES IS AT YOUR OWN RISK. YOU ARE SOLELY RESPONSIBLE FOR YOUR USER CONTENT, THE REPRESENTATIONS AND OBLIGATIONS UNDER THIS Submission Agreement AND FOR ANY DAMAGES TO YOUR COMPUTER SYSTEM OR LOSS OF DATA RESULTING FROM YOUR USE OF THE SITE OR USER CONTENT SUBMISSION FEATURES. the Parent Company AND THE Parent Company EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES, INCLUDING, WITHOUT LIMITATION, WARRANTIES CONCERNING ACCESS TO AND/OR THE AVAILABILITY, ACCURACY, USEFULNESS AND/OR SECURITY OF THE SITE OR USER CONTENT SUBMISSION FEATURES, ANY CONTENT, MATERIAL, SOFTWARE, INFORMATION, DATA, SOFTWARE, CAPABILITIES MADE AVAILABLE TO YOU, RESOURCES, FACILITIES, PRODUCTS AND/OR SERVICES, AND WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE OR THAT THE USER CONTENT SUBMISSION FEATURES WILL FUNCTION OR PERFORM IN ANY PARTICULAR MANNER.

THE SITE AND USER CONTENT SUBMISSION FEATURES ARE MAINTAINED ON SERVERS IN THE UNITED STATES INTENDED FOR USERS AND USE OF THE USER CONTENT SUBMISSION FEATURES THAT ARE NOT RESTRICTED OR PROHIBITED BY LAW OR REGULATION. the Parent Company AND THE Parent Company DISCLAIMS ALL LIABILITY FOR ANY USE NOT SPECIFICALLY AUTHORIZED OR THAT IS IN VIOLATION OF THIS Submission Agreement OR THE LAWS OR REGULATIONS THAT MAY APPLY TO YOU IN ANY JURISDICTION OR COUNTRY. the Parent Company AND THE Parent Company EXPRESSLY DISCLAIMS ALL LIABILITY FOR ANY AND ALL DAMAGES, WHETHER DIRECT, CONSEQUENTIAL, SPECIAL, INDIRECT, EXEMPLARY OR PUNITIVE DAMAGES, HOWSOEVER ARISING OR CAUSED, WHETHER FORESEEABLE OR NOT, REGARDLESS OF THE FORM OF ACTION OR THE BASIS OR CHARACTERIZATION OF THE CLAIM AND EVEN IF ADVISED OF THE POSSIBILITY OF DAMAGES.

<li><h2>General.</h2></li>
The <a href="<?php echo getUrl("terms-of-service/"); ?>">Terms of Service Agreement</a>, incorporating this Submission Agreement, is the entire agreement between you and us relating to User Content and your use of the User Content Submission Features and supersedes any prior or inconsistent agreements. the Parent Company may terminate this Submission Agreement with you and your right to use the User Content Submission Features at any time without notice to you.